beagleboard/bb.org-overlays

Makefile
src/arm/bone_eqep0.dts
src/arm/bone_eqep1.dts
src/arm/bone_eqep2.dts
src/arm/bone_eqep2b.dts

Please add these two commits to origin.

add tieqep overlays & DESTDIR support in Makefile

---

src/arm/BB-ADC-00A0.dts
src/arm/BB-UART1-00A0.dts
src/arm/BB-UART2-00A0.dts
src/arm/BB-UART3-00A0.dts
src/arm/BB-UART4-00A0.dts
src/arm/BB-UART5-00A0.dts
src/arm/bone_eqep0-00A0.dts
src/arm/bone_eqep1-00A0.dts
src/arm/bone_eqep2-00A0.dts
src/arm/bone_eqep2b.dts

add partially functional BB-UART3, remove pullups & pulldowns from UARTS, add RTSn and CTSn, fix AIN0 exclusive-use 

---

src/arm/BB-BONE-4D5C-01-00A1.dts

touchscreen was not aligned with picture

inverted touchscreen axis

---

src/arm/seeed-4mic-voicecard-00A0.dts

The 4mic voicecard detailed at https://github.com/respeaker/seeed-voicecard/.

Add: seeed-4mic-voicecard support

---

src/arm/PB-simplegaming.dts

I really need to find an official name for this PocketCape.

PB-simplegaming.dts: create

---

src/arm/PB-SPI1-OLEDC-CLICK.dts

OLEDC Click board device tree overlay file for PocketBeagle

OLEDC Click device tree overlay

---

src/arm/PB-SPI0-OLEDC-CLICK.dts
src/arm/PB-SPI1-OLEDC-CLICK.dts

- Fix links, copyright
- Enable GPIO on boot up to enable display
- Add SPI0 overlay file

DTO support for OLED C display click boards

---

src/arm/BB-I2C2-RTC-DS1307.dts

Add overlay for RTC DS1307

---

src/arm/BBORG_RELAY-00A2.dts

Can someone tell me how to control one of these relays using C code ???

Add an initial BBORG_RELAY-00A2.dts file

---

src/arm/BB-SPI0-AT86RF233-00A0.dts

Thoroughly tested on the BeagleBone Black Rev C. Kernel version: Linux beaglebone 4.14.71-ti-r80

Device tree for the ATMEL AT86RF233 IEEE802.15.4 Transceiver

---

src/arm/PB-I2C1-TLV320AIC3104.dts

This sound cap overlay applied to Grove-Base-Cape which used with PocketBeagle.

Add: audio sound card tlv320aic3104 on Grove-Base-Cape

---

BB-UART2-00A1.dts

If someone wants to use beaglebone green gateway's grove uart interface, this dts will be very helpful

add BB-UART2-00A1.dts

---

extras/tlv320aic3104.conf.txt
src/arm/BB-I2C2-ADXL34X.dts

use the iio devices
https://github.com/beagleboard/linux/blob/4.14/drivers/iio/accel/adxl345_i2c.c#L53

For adxl34x, use an iio driver

---

src/arm/BBORG_GAMEPUP-00A2.dts

Please have Jason review before merging.
He has a blog post that incorporates the contents of the modified
devicetree source file.

Overlay new format BBORG_GAMEPUP-00A2

---

src/arm/BBAI_BBORG_COMMS-00A2.dts

@RobertCNelson Please review my code.

BBBAI comms cape overlay

---

src/arm/BBAI_BBORG_MOTOR-00A2.dts

@RobertCNelson please review my code :)

BBBAI Motor Cape overlay

---

src/arm/BBAI_BBORG_RELAY-00A2.dts

@RobertCNelson Please review my code :)

BBBAI Relay Cape overlay

---

src/arm/BBORG_LOAD-00A2.dts

@RobertCNelson please review my code :) 
I don't know why the indentation looks off here, it looks good on the local machine. 
Also, I wanted to ask you if you have ever used the LCD7/LCD4 Cape with BBB/BBAI, If yes can you let me know the process?

BBB Load Cape overlay

---

src/arm/EEPROM.dts
src/arm/PB-USB0-HOST.dts
src/arm/PB-USB1-OTG.dts
src/arm/PB-USB1-PERIPHERAL.dts
src/arm/PB-eqep2.dts

New overlays: USB, EEPROM, EQEP

---

src/arm/BB-I2C1-RTC-DS3231.dts

Had some silly issues getting this DS3231 Real Time Clock to work on I2C1 (instead of the more common I2C2). Figure this can help someone out.

DS3231 I2C1 DTS File

---

src/arm/M-BB-OSD3358-SM-RED-00A1.dts

Signed-off-by: Matt Ranostay <matt.ranostay@konsulko.com>

add M-BB-OSD3358-SM-RED-00A1.dts

---

tools/pmunts_muntsos/config-pin.c

- added `#define PLATFORMBASE "/sys/devices/platform/ocp/"`
- `GetGpio()` has extra argument to handle returning gpio to the terminal
- `QueryMode()` has extra argument for removing new line for `ListAllPins()`
- `extract_pin_name()` uses `PLATFORMBASE` to return all Physical pin names
- `main()` has additional check for `-g` and -a`"

feat: return all pins, with gpio number, current state & all modes
