- src/arm/BB-BONE-BACONE-00A0.dts
Fixes https://github.com/RobertCNelson/bb.org-overlays/issues/3
> BB-BONE-BACONE-00A0.dts: hardware ip should use gpio0_22 for P8.19

- include/dt-bindings/board/am335x-bbw-bbb-base.h
- include/dt-bindings/gpio/gpio.h
- include/dt-bindings/pinctrl/am33xx.h
- src/arm/BB-I2C1-00A0.dts
- src/arm/BB-UART1-00A0.dts
- src/arm/BB-UART2-00A0.dts
- src/arm/BB-UART4-00A0.dts
- src/arm/BB-UART5-00A0.dts
- src/arm/bone_eqep0-00A0.dts
- src/arm/bone_eqep1-00A0.dts
- src/arm/bone_eqep2-00A0.dts
- src/arm/bone_eqep2b.dts
I have a kernel patch for tieqep.c which supports count_mode <2> & <3>.  It still needs some code formatting, as the original driver could never be accepted into mainline since it uses C++ comments and spaced instead of tabs.
The advantage of count_modes 2 & 3 are that the direction input is fixed and you don't need a pin to determine direction.   Useful for frequency inputs.  count_mode is not the same as userspace "mode" (absolute vs. relative).  Three of the count_modes all pertain typically to userspace "mode" == relative.
> avoid uart1.i2c2 pins in BB-UART1, add additional count_mode support in eqep

- Makefile
If ```/lib/firmware``` doesn't exist, ```make install``` fails:
```
cp -v src/arm/*.dtbo /lib/firmware/
cp: target ‘/lib/firmware/’ is not a directory
Makefile:142: recipe for target 'install_arch' failed
make[1]: *** [install_arch] Error 1
Makefile:88: recipe for target 'install_arm' failed
make: *** [install_arm] Error 2
```
> ensure installation directory exists

- src/arm/cape-universal-00A0.dts
- src/arm/cape-universala-00A0.dts
- src/arm/cape-universaln-00A0.dts
Allows use of the very handy PRU UART and eCAP peripherals
Signed-off-by: Charles Steinkuehler <charles@steinkuehler.net>
> Add PRU domain peripherals

- src/arm/ACME-revB.dts
This overlay is for the BayLibre ACME cape that can be found at: http://baylibre.com/acme/
> Add ACME revB cape overlay

- src/arm/cape-universala-00A0.dts
I had to modify `cape-universala-00A0.dts` to enable pins `P8_33` and `P8_35` for eqep1
> enable eqep1 for pins p8.33 and p8.35

- src/arm/BB-SPI0-ADS6888-0A00.dts
- tools/beaglebone-universal-io/README.md
This commit adds BB-SPI0-AD8688-0A00.dts
this will support the ti ad8688 device connected to spi0
I am not sure this is really needed, and i have the feeling
that a smaller .dts override could disable a spidev channel and add the
adb child to the spi node, however, i was unable to get that working.
there are also small fixes on documentation that i could not remove
from the pull request. I am a newbie here.
> Add a DTS for AD8688 via SPI0

- src/arm/BB-I2C1-FAST-00A0.dts
- src/arm/BB-I2C2-FAST-00A0.dts
The AM335x supports both 100kHz and 400 kHz clock speeds on its i2c buses. This branch adds overlays that allow you to generically enable the i2c buses at the faster clock speed. I've been using this for a while with no problems. I thought this might be useful to have upstream.
These are literally just a copy of the base i2c overlays with `clock-frequency` changed to `<400000>`. If there is a better way to do this, let me know.
Signed-off-by: Jacob Creedon <jcreedon@gmail.com>
> Add overlays for 400kHz (FAST) i2c on both user buses

- src/arm/BB-LCD-ADAFRUIT-18-SPI1-00A0.dts
* This file was copied from `src/arm/BB-SPIDEV1-00A0.dts` and modified by Drew Fustini (@pdp7) based on an exmample from David Lechner (@dlech).
* [Adafruit 1.8" TFT LCD](https://www.adafruit.com/products/358) should be connected to SPI1 bus.
* This overlay will load the [tinydrm st7735r driver](https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/tinydrm/st7735r.c) by David Lechner (@dlech):
* Tested with 4.16.0-rc2-bone3 kernel on Debian 9.3 image
* [Run libdrm modetest for colorbar test](https://github.com/notro/tinydrm/wiki/Development#modetest):
```
modetest -M "st7735r" -c #this will display connector id
modetest -M "st7735r" -s 28:128x160 #connector id and resolution
```
* [Mailing list post](https://groups.google.com/d/msg/beagleboard/GuMQIP_XCW0/b3lxbx_8AwAJ) with more …
> Add overlay for Adafruit 1.8" TFT LCD on SPI1 with tinydrm st7735r

- src/arm/BB-LCD-ADAFRUIT-18-SPI1-00A0.dts
Add defintion for GPIO backlight control on Adafruit 1.8" TFT LCD.
Connect `lite` pin on lcd to [`P9.23`](https://elinux.org/Beagleboard:Cape_Expansion_Headers)
> BB-LCD-ADAFRUIT-18-SPI1: add definition for backlight control

- src/arm/BB-LCD-ADAFRUIT-18-SPI1-00A0.dts
Add definition for PWM backlight control on Adafruit 1.8" TFT LCD.
**Instructions:**
* Connect lite pin on lcd to P9.14.
* Turn on backlight on by setting `bl_power` to `0` _(`FB_BLANK_UNBLACK`)_ per [comment](https://github.com/beagleboard/bb.org-overlays/pull/68#issuecomment-371281619) by @notro in PR #68:
```
echo 0 > /sys/devices/platform/backlight_pwm/backlight/backlight_pwm/bl_power
```
NOTE: `FB_BLANK_UNBLACK` is specified in [sysfs-class-backlight](https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-backlight)
> BB-LCD-ADAFRUIT-18-SPI1: add pwm backlight on P9.14

- src/arm/AM335X-PRU-RPROC-4-9-TI-PRUCAPE-00A0.dts
Not sure if this is the recommended approach to getting the PRU Cape up and running with 4.9.x kernels, but it's working well for me so far under 4.9.88-ti-r111.
> add prucape overlay (v4.9.x-ti/rproc)

- src/arm/BB-UART1-RTSCTS-00A0.dts
- src/arm/BB-UART4-RTSCTS-00A0.dts
- src/arm/BB-UART5-RTSCTS-00A0.dts
Details of Yantrr INDU-RS capes with and without DC-DC converter : 
- http://yantrr.com/products/industrial-capes
- https://www.yantrr.com/wiki/INDU-RS#Overview
Utilizing Modbus protocol, these capes can be used to transform Yantrr's VIBE/VIBEQ/VIBE2 IoT platform into powerful SCADA & process control systems. INDU-RS capes are fully compatible with BeagleBone CPU platform.
> Add : additional overlays to support Yantrr INDU-RS capes

- src/arm/BB-BELA-B2.dts
The `BB-BELA-B2.dts` overlay will now work on both BBx and PB devices.
We use different pins for our GPIOs on the two boards. These are handled as follows:
On the PB:
- `fragment@0` disables the "universal" pins
- `fragment@7` re-enables them with a different default value
- `fragment@8`fails to apply
- `config-pin` can be used to manually change the function of those pins.
- we now support uboot overlays as well.
On the BBx:
- `fragment@0` fails to apply (the `Px_xx_pinmumx` do not exist)
- `fragment@7` fails to apply
- `fragment@8` applies successfully 
- more overlays can be added with `capemgr` or uboot overlays
> Finished off the Bela overlay

- src/arm/MCP2515-SPI0.dts
From https://github.com/battlesnake/beaglebone-spi0-mcp2515/blob/master/MCP2515.dts
by Mark K Cowan
GitHub gist:
https://gist.github.com/pdp7/20dddbeffe83082e3c94ab0903563783
Wire the MCP2515 to SPI0 on the BeagleBone Black:
https://photos.app.goo.gl/1UUAHhRngzwiVWha9
add this to /boot/uEnv.txt:
uboot_overlay_addr0=/lib/firmware/BB-SPIDEV0-00A0.dtbo
uboot_overlay_addr1=/lib/firmware/MCP2515.dtbo
> add MCP2515 overlay by Mark K Cowan

- tools/beaglebone-universal-io/config-pin
1. Presently, config-pin accepts "inp**d**t_pd" but not "inp**u**t_pd".
2. The three commands used to read and process /proc/device-tree/model into "machine" can be condensed into a single call to sed. This should save a little execution time.
> config-pin bug, efficiency improvement

- src/arm/PB-MCP2515-SPI1.dts
This adds support for the MCP2515 CAN controller on the Macchina PocketBeagle
> add support for the Macchina PocketBeagle adapter

- src/arm/BB-I2C2-RTC-DS3231.dts
Tested only on element14 BeagleBone Industrial
Have not tested on the beaglebone green but it is included as a compatible device.
> Device tree for the maxim DS3231 Real Time Clock,

- src/arm/AM335X-PRU-RPROC-4-14-TI-00A0.dts
- src/arm/AM335X-PRU-RPROC-4-19-TI-00A0.dts
- src/arm/AM335X-PRU-RPROC-4-4-TI-00A0.dts
- src/arm/AM335X-PRU-RPROC-4-9-TI-00A0.dts
Note that https://github.com/mvduin/py-uio/blob/master/etc/modprobe.d/uio.conf is required to make this work.
> pru shared memory example 1 (one device, multiple memories)

- src/arm/BB-BONE-WL1837-00A0.dts
- src/arm/BB-GATEWAY-WL1837-00A0.dts
WL_EN is on P9_22 and WL_IRQ is on P9_42, as stated in [element14 pinout](https://www.element14.com/community/servlet/JiveServlet/showImage/105-89801-307334/CapeExpansionHeadersP9wGatewayFunctions.jpg).
Wrong GPIO hog definition for some pins, i.e., it should be `gpios` instead of `gpio`.
> Fixes for BB-GATEWAY-WL1837-00A0.dts and BB-BONE-WL1837-00A0.dts

- src/arm/BBAI_BB-BONE-LCD4-01-00A1.dts
@RobertCNelson Please review my code :)
The confusion of why I2C1 is a target for touch controller is resolved when ds2 shared this schematic https://www.openhacks.com/uploadsproductos/beaglebone-lcd4-reva1-schematic.pdf
> add BBAI LDC4 cape overlay

- tools/pmunts_muntsos/config-pin.c
With these changes, pins can be configured with "in" and "out" modes. These modes were available in the [`config-pin`](https://github.com/beagleboard/bb.org-overlays/blob/master/tools/beaglebone-universal-io/config-pin) shell script that was used prior to switching to the C version. With the "in" mode, a pin is configured as a gpio and its direction is set to input. Similarly, with the "out" mode, a pin is configured as a gpio and its direction is set to output.
To implement this, I needed to obtain the GPIO number (e.g. gpio110) for any pin (e.g. P1_36) entered by the user. I use subprocesses to achieve this; in particularly, I call utilities from [`libgpiod`](https://github.com/brgl/libgpiod) that are included with the Debian image. There are alternatives to this approach -- e.g., …
> Add in/out modes to config-pin

- src/arm/PB-PWM-TIMER-P1.20.dts
- src/arm/PB-PWM-TIMER-P1.26.dts
- src/arm/PB-PWM-TIMER-P1.28.dts
- src/arm/PB-PWM-TIMER-P2.27.dts
- src/arm/PB-PWM-TIMER-P2.31.dts
Add device tree overlays for using the DMTimer pins on the PocketBeagle. These overlays are analogous to the ones added in 563af29 for the BeagleBone Black. With these overlays, the following pins can be used for PWM on the PocketBeagle:
- P1_20
- P1_26
- P1_28
- P2_27
- P2_31
These overlays have been tested on the 2020-07-13, Buster IoT testing image "bone-debian-10.4-iot-armhf-2020-07-13-4gb.img.xz," running on PocketBeagle. Additionally, they have been tested on the currently recommended Debian image ("AM3358 Debian 10.3 2020-04-06 4GB SD IoT").
> Add PocketBeagle DMTimer overlays

- tools/pmunts_muntsos/config-pin.c
@RobertCNelson @jadonk please review my code :) 
A conditional block has been added to detect the board type. The conditional block depends on the macro created in the compatibility layer code. Tested config-pin on BBAI with the compatibility layer installed.
> Fix config-pin for BBAI

- src/arm/PB-MIKROBUS-0.dts
- src/arm/PB-MIKROBUS-1.dts
Hi @RobertCNelson ,
This is a minor update in the overlay which will be required for testing GNSS/GPS Clicks.
add force-empty-serdev-controller field, this is necessary to create an empty serdev controller(when there is no serdev child nodes defined in DT).
> Update MIKROBUS PB Overlays

- src/arm/BB-SPI0-CC2520-00A0.dts
CC2520 cape using
SPI0 on connector pins P9.22 P9.21 P9.18 P9.17
and 6 GPIOS pins P8.11 P8.12 P8.15 P8.16 P9.12 P9.23
> Add: overlay of cc2520 cape on SPI0

- src/arm/BB-MIKROBUS-CAPE-1.dts
- src/arm/BB-MIKROBUS-CAPE-2.dts
- src/arm/BB-MIKROBUS-CAPE-3.dts
- src/arm/BB-MIKROBUS-CAPE-4.dts
Hi @RobertCNelson ,
Tested on BeagleBone Black Wireless with the mikroBUS cape and miikroBUS driver latest patch(serdev), should
work perfectly with the previous/v2 patch as well.Original Pull request submission: https://github.com/beagleboard/bb.org-overlays/pull/200 was closed accidentally.
Changes from original PR:
- @RobertCNelson  's suggested fix to split all spi1 pins to a common
pinmux same for all the overlays(port 1,2,4)- tested with SPI clicks
on the ports.
- rename mikrobus alias from 0-indexed to 1-indexed so that there is no confusion 
between ports on the mikrobus cape.
> mikrobus: Add Overlays for mikroBUS Cape Ports

- src/arm/BB-BONE-WL1835MOD-00A0.dts
Overlay for CircuitCo WL1835MOD cape, see https://github.com/CircuitCo/WL1835MOD 
I merely converted the file 
https://github.com/beagleboard/linux/blob/4.19/arch/arm/boot/dts/am335x-boneblack-wl1835mod-cape.dtsi
to overlay format.  
I tried to minimize diffs, see screenshot. Since I'm totally new to this, happy to get your feedback and adjust as needed.
Works for me using:
`model:[TI_AM335x_BeagleBone]`
`BeagleBoard.org Debian Buster IoT Image 2020-04-06`
`Linux beaglebone 4.19.94-ti-r55 #1buster SMP PREEMPT Tue Oct 27 21:48:45 UTC 2020 armv7l GNU/Linux`
> Overlay for CircuitCo WL1835MOD cape

- src/arm/BB-SPI1-LTC2947-00A0.dts
I've tested this with 2x [VCP Monitor 3 click](https://www.mikroe.com/vcp-monitor-3-click) boards in slots 1 & 2 of the MikroBus cape.
For linux kernel driver support, you need to update to kernel 5.4.70-ti-r19 (or another 5.4.x), then compile and install the modules from mainline. I've made a small repo for out-of-tree module compilation [here](https://gitlab.com/bluesquall/kmod-ltc2947) (and I'll probably mirror it on github later).
> add dts for LTC2947 on SPI1 of BeagleBoneBlack

- src/arm/BB-I2C1-ADS1115.dts
The ADS1115 is a popular ADC IC. There are some modules based on it.
It was tested using a similar [Adafruit Breakout Board](https://www.adafruit.com/product/1085) and [ADS1015 device driver](https://www.kernel.org/doc/html/v5.2/hwmon/ads1015.html).
> added overlay of ADS1115 on I2C1

- src/arm/PB-BONE-AUDI-02-00A0.dts
- src/arm/PB-I2C2-TLV320AIC3104.dts
As discussed [here ](https://forum.digikey.com/t/getting-started-with-a-custom-audio-cape/18300/30?u=wesperos), a dts for audio cape on PocketBeagle wont work if we simply copy BB-BONE-AUDI-02-00A0 and change pinmux, It will work if we take the existing dts for the codec (PB-I2C1-TLV320AIC3104) and modify the I2C instance. Here I share the codec dts for i2c2 as well as the audio cape dts.
> DTS for Audio cape on PB
